// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtfacnuanjvpvzezglgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZmFjbnVhbmp2cHZ6ZXpnbGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjE0ODIsImV4cCI6MjA3MTMzNzQ4Mn0.W9a6UdoEH1yThn5P2q1DUz821FRIox7GxODSkFXsBG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});